### ISSUE TITLE
你好，关于论文和代码不一致问题

### ISSUE THREAD

**Issue by OvOYu** [Dandelionym/CDVGM#2]
https://github.com/Dandelionym/CDVGM/blob/main/model/core.py#L40  这里的代码是在最后一个维度拼接 论文里说的是倒数第二个 并且拼接后张量并没有改变  请问是否有问题

**Comment by Dandelionym** [comment]
Thank you for reaching out! In the code you referred, that’s a redundant step based on the original code in CDVGM (as it is for the concat of week, day and hour data in DGCN), so that’s not related to our design. 

If you have any other problem, welcome to leave here. Thank you! 😊
